### ISSUE TITLE
Caliber wallet incorrect balance / not working

### ISSUE THREAD

**Issue by cyclane** [caliber-cash/caliber#2]
I am mining with XMR-Stak and using the `caliber.luckypool.io:5566` pool and I have apparently been paid 5.02 CAL however in my wallet, even after updating it I have 0. This might be a problem with the pool but I'll also submit this just in case anyone else has this issue.

EDIT: I am currently trying a different pool `cal.rubypool.com:3333`, if this works I'll close this issue.

**Comment by bymaximus** [comment]
+1
